In [4]:
import numpy as np
def f(x,y):
    return 10*x+y
b=np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [23]:
for i in b.flat:
    print(i)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [25]:
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [26]:
a[a>50]

array([60, 70, 80, 90])

In [28]:
!pip install pandas matplotlib xlrd

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 16.7 MB 3.3 MB/s eta 0:00:01
     |████████████████████████████████| 103 kB 6.7 MB/s eta 0:00:01
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 13.9 MB 7.9 MB/s eta 0:00:01
     |████████████████████████████████| 516 kB 3.9 MB/s eta 0:00:01
     |████████████████████████████████| 154 kB 4.7 MB/s eta 0:00:01
  Created wheel for tornado: filename=tornado-5.1.1-cp27-cp27m-macosx_10_15_x86_64.whl size=451484 sha256=36d01e207c54533119f2